# Generated by Django 2.2.2 on 2019-07-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us_login',
            name='id',
        ),
        migrations.AlterField(
            model_name='contact_us_login',
            name='roll_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
